#!/usr/bin/env python3
"""
This script checks whether premake generates the same tutorial files as the last time --update was called.
Useful when updating tutorials.lua or to catch unintended renames.

Note: No checks are run on the actual code, so that has to be tested in other ways.
Note: Warnings printed by the generator are always shown, but do not affect the test itself.

Usage:
    python3 Scripts/check_tutorial_projects.py            # check
    python3 Scripts/check_tutorial_projects.py --update   # re-record the baseline

Exit codes: 0 = matches baseline, 1 = drifted, 2 = could not run the generator.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_BASELINE = SCRIPT_DIR / "tutorial_projects.txt"

PREMAKE_ACTION = "gmake"
PREMAKE_OPTIONS = ["--cpp", "--vulkan", "--no-examples"]

SDK_ENV_VARIABLES = ("OCL_ROOT", "INTELOCLSDKROOT", "CUDA_PATH", "VULKAN_SDK")

# Tutorial projects always start with a digit.
TUTORIAL_PROJECT = re.compile(r"^[0-9]")

# Lines the generator uses to report a problem it does not stop for.
GENERATOR_WARNING = re.compile(r"^Warning:")


class GeneratorError(Exception):
    """The generator could not be run, so the project set is unknown."""


def echo_generator_warnings(output):
    """Repeat the warnings of the generator, which the check itself does not act on."""
    for line in output.splitlines():
        if GENERATOR_WARNING.match(line):
            print(line)


def find_premake(override=None):
    """Return the premake command to run."""
    if override:
        return [override]

    for candidate in ("premake5", "premake"):
        found = shutil.which(candidate)
        if found:
            return [found]

    raise GeneratorError(
        "Premake was not found on PATH. Install Premake 5 (https://premake.github.io/download)\n"
        "or point --premake at the executable, or set the PREMAKE environment variable."
    )


def generate_project_set(premake, tmpdir, verbose=False):
    """Generate the project files into a scratch directory and return the tutorial project names."""
    stub_sdk = tmpdir / "sdk-stub"
    stub_sdk.mkdir(parents=True, exist_ok=True)
    generated = tmpdir / "projects"
    generated.mkdir(parents=True, exist_ok=True)

    environment = dict(os.environ)
    for variable in SDK_ENV_VARIABLES:
        environment[variable] = str(stub_sdk)

    command = premake + [PREMAKE_ACTION, *PREMAKE_OPTIONS, f"--outdir={generated}"]
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    if verbose:
        sys.stdout.write(result.stdout)
    else:
        echo_generator_warnings(result.stdout)

    if result.returncode != 0:
        tail = "\n".join(result.stdout.splitlines()[-20:])
        raise GeneratorError(f"Premake generation failed (exit {result.returncode}):\n{tail}")

    projects = sorted(
        makefile.stem
        for makefile in generated.glob("*.make")
        if TUTORIAL_PROJECT.match(makefile.stem)
    )

    if not projects:
        raise GeneratorError(
            "Generation produced no tutorial projects. The tutorial folders may have been renamed\n"
            "so that they are no longer found, or generation may have skipped them."
        )

    return projects


def load_baseline(path):
    """Read the recorded project names, ignoring blank lines and comments."""
    if not path.is_file():
        raise GeneratorError(f"Baseline file not found: {path}\nCreate it with: --update")

    names = []
    for line in path.read_text().splitlines():
        entry = line.split("#", 1)[0].strip()
        if entry:
            names.append(entry)
    return names


def write_baseline(path, projects):
    """Record the generated project set as the new baseline."""
    header = (
        "# Tutorial projects generated by Tutorials/tutorials.lua with all compute APIs enabled.\n"
        "# Update after an intended change to the tutorial folders:\n"
        "#     python3 Scripts/check_tutorial_projects.py --update\n"
    )
    path.write_text(header + "".join(f"{project}\n" for project in projects))


def display_path(path):
    """Show a path relative to the repository root when it lives inside it."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def format_drift(expected, actual):
    """Describe the difference between the recorded and generated project sets."""
    removed = sorted(set(expected) - set(actual))
    added = sorted(set(actual) - set(expected))

    lines = ["Generated tutorial projects do not match the recorded baseline.", ""]
    if removed:
        lines.append(f"  removed ({len(removed)}):")
        lines.extend(f"    - {project}" for project in removed)
    if added:
        if removed:
            lines.append("")
        lines.append(f"  added ({len(added)}):")
        lines.extend(f"    + {project}" for project in added)
    lines.append("")
    lines.append(f"  baseline: {len(expected)} projects, generated: {len(actual)} projects")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--update", action="store_true",
                        help="record the currently generated project set as the new baseline")
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE,
                        help="baseline file to compare against (default: Scripts/tutorial_projects.txt)")
    parser.add_argument("--premake", default=os.environ.get("PREMAKE"),
                        help="premake executable to run (default: premake5 or premake on PATH)")
    parser.add_argument("--verbose", action="store_true", help="show the generator output")
    args = parser.parse_args(argv)

    baseline = args.baseline if args.baseline.is_absolute() else Path.cwd() / args.baseline

    try:
        premake = find_premake(args.premake)
        with tempfile.TemporaryDirectory(prefix="ktt-tutorial-projects-") as tmp:
            projects = generate_project_set(premake, Path(tmp), verbose=args.verbose)
    except GeneratorError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.update:
        write_baseline(baseline, projects)
        print(f"Recorded {len(projects)} tutorial projects in {display_path(baseline)}")
        return 0

    try:
        expected = load_baseline(baseline)
    except GeneratorError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if expected == projects:
        print(f"OK: generation produces the {len(projects)} recorded tutorial projects.")
        return 0

    print(format_drift(expected, projects))
    print("If this change is intended, re-record the baseline with:")
    print(f"    python3 {display_path(Path(__file__))} --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())
